name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Install NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Generated Package
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release
    - name: Publish Package
      run:
        dotnet nuget push ./src/DotNetCore.CAP.Sqlite/bin/Release/*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
